[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
linker = "aarch64-none-elf-ld" #GNU ARM toolchain installs the linker as aarch64-none-elf-ld (not aarch64-linux-gnu-ld like on Linux)
# -C link-arg=-Tlinker.ld tells Rust to use our custom linker script
rustflags = ["-C", "link-arg=-Tlinker.ld"]
